export const galleryCopy = {
  eyebrow: "Gallery / Archive",
  title: "Gallery",
  description:
    "Browse the archive by timeline or media type and trace the light of each shoot.",
  scrollMore: "Scroll to load more",
  loadingMore: "Loading more...",
  allLoaded: "All content loaded",
  loadError: "Failed to load more content.",
  retryLoad: "Retry",
  backToTop: "Back to top",
  searchPlaceholder: "Search title, trip, or caption",
  searchAria: "Search gallery content",
  clearSearch: "Clear search",
  noResults: "No matching content. Try a shorter keyword.",
  people: {
    eyebrow: "Gallery / People",
    title: "People Gallery",
    description: "Browse photos by person, sorted A–Z.",
    empty: "No tagged people yet. Add person tags when editing a photo.",
    noPhotos: (name: string) => `No photos tagged with ${name} yet.`,
  },
  places: {
    eyebrow: "Gallery / Places",
    title: "Places Gallery",
    description:
      "Browse photos by place, sorted A–Z. Trips sharing the same folder name are combined.",
    empty: "No trips with photos yet.",
    noPhotos: (name: string) => `No photos in ${name} yet.`,
  },
  filters: {
    all: "All",
    photo: "Photo",
    video: "Video",
    timeline: "Timeline",
    newest: "Newest First",
    oldest: "Oldest First",
  },
  grid: {
    summary: (visible: number, total: number) =>
      `Showing ${visible} / ${total} items`,
    columns: {
      label: "Per row",
      aria: "Items per row",
      count: (count: number) => `${count} cols`,
    },
    timestamps: {
      on: "Timestamps",
      off: "Hide timestamps",
    },
    tags: {
      on: "Tags",
      off: "Hide tags",
    },
    modal: {
      closeAria: "Close",
      keyboardShortcuts: "Keyboard Shortcuts",
      shortcuts: {
        prevNext: "Previous/Next",
        close: "Close",
      },
      authorPrefix: "Captured by",
      authorFallback: "Vacations",
      dateFallback: "--",
      untitled: "Untitled",
      share: "Share",
      shareCopied: "Share link copied",
      download: "Download",
      trip: "Trip",
      location: "Location",
      size: "File size",
      captured: "Captured",
      details: "Image details",
      hideDetails: "Hide details",
      back: "Back",
      addFavoriteTag: "Add Favorite Tag",
      removeFavoriteTag: "Remove Favorite Tag",
    },
  },
} as const;
